#! /usr/bin/php
<?php
require "vendor/autoload.php";

use App\DotenvLoad;
use App\DropboxClient;
use Dotenv\Dotenv;
use App\Service\DoctrineManager;
use App\Entity\LogCdr;

$currentPath = __DIR__;

$dotenv = Dotenv::createImmutable($currentPath);

$envLoad = new DotenvLoad($dotenv);

$manager = new DoctrineManager();

$doctrine = $manager->getDoctrine();

/**
 * @var LogCdr
 */
$logCdr = $doctrine->getRepository(LogCdr::class)->findOneBy(['uniqueid' => '1616153143.306']);

$logCdr->setLinkMp3('asdasdas');

$doctrine->flush();

$handleDropbox = new DropboxClient();

$app = $handleDropbox->getDropbox()->createSharedLinkWithSettings('asdaisjda/composer.json');