#! /usr/bin/php
<?php
require "vendor/autoload.php";

use App\Utils;
use Garden\Cli\Cli;

// https://www.dropbox.com/oauth2/authorize?client_id=<APP_KEY>&response_type=code&token_access_type=offline
// ./dropbox-make-refresh-token --code="CODE" --refresh_token="REFRESH_TOKEN"

$cli = new Cli();
$cli->opt('code:c', 'authorization code temporario')->opt('refresh_token:r', 'refresh token se já tiver');

$args = $cli->parse($argv);

try {
       if ($args->get('refresh_token')) {
              file_put_contents(__DIR__ . "/refresh_token.txt", $args->get('refresh_token'));
       } else if ($args->get('code')) {

              $code = $args->get('code');

              $currentPath = __DIR__;

              $utils = new Utils();

              $result = $utils->generateRefreshTokenFile($code, $currentPath);

              $refreshToken = $result['refresh_token'];

              file_put_contents(__DIR__ . "/refresh_token.txt", $refreshToken);

              echo "{$refreshToken}\r\n";
       } else {
              throw new \Exception("Não foi passado o parametro 'code' ou 'refresh_token'");
       }
} catch (\Exception $e) {
       echo $e->getMessage() . "\r\n";

       if (!array_key_exists('APP_KEY', $_ENV) || !array_key_exists('APP_SECRET', $_ENV)) {
              echo "nenhuma APP_KEY ou APP_SECRET encontrada, atualize o arquivo env\r\n";
              return;
       }

       $link = "https://www.dropbox.com/oauth2/authorize?client_id={$_ENV['APP_KEY']}&response_type=code&token_access_type=offline";
       echo "para gerar um code_autorization e gerar um refresh_token válido acesse essa url:\r\n{$link}\r\n";
}
