#! /usr/bin/php
<?php
require "vendor/autoload.php";

use App\Run;

$currentPath = __DIR__;

$run = new Run($currentPath, $argv);

$dropboxReponse = $run->dropboxReponse();

echo json_encode($dropboxReponse);