#! /usr/bin/php
<?php
require "vendor/autoload.php";

use App\CommandLine;
use App\DotenvLoad;
use App\FileUploader;
use Dotenv\Dotenv;

$dotenv = Dotenv::createImmutable(__DIR__);

$cli = new CommandLine($argv);
$envLoad = new DotenvLoad($dotenv);

$cli->start();

$fileUploader = new FileUploader($cli);

$fileUploader->upload();